#!/bin/bash

# Launcher script for graphical linux applications executed on WSL via Windows command line. Can be used within a symbolic Windows link.
# Example:
# wsl -u myusername -- start-app "myapp"
# wsl.exe -u lespirou -- start-app "eclipse"
# Symbolic Windows Link example:
# C:\Windows\System32\wsl.exe -u lespirou -- start-app "eclipse"

export SWT_GTK3=1

export LIBGL_ALWAYS_INDIRECT=1

if [ $(grep -oE 'gcc version ([0-9]+)' /proc/version | awk '{print $3}') -gt 5 ]
then
    export WSL_VERSION=2
    export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
# export DISPLAY="`grep nameserver /etc/resolv.conf | sed 's/nameserver //'`:0"
else
    export WSL_VERSION=1
	export DISPLAY=localhost:0.0
fi

cd ~

$*
